/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package takestones;

import org.junit.jupiter.api.Test;

class TakeStonesTest {
    @Test
    void appHasAGreeting() {
        TakeStones classUnderTest = new TakeStones();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
